routes/web.php
<?php

use App\Http\Controllers\ArticlesController;
use App\Http\Controllers\ArticlesJsonController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \App\Http\Controllers\DemoController;

Route::get('/', [DemoController::class, 'index'])->name('home');

Route::get('/users/{name}', [DemoController::class, 'name'])->whereAlphaNumeric('name')->name('name');

Route::get('/contact', [ContactController::class, 'index'])->name('contact.index');
Route::post('/contact', [ContactController::class, 'submit'])->name('contact.submit');

Route::prefix('blog')->group(function() {
    Route::get('/', [ArticlesController::class, 'index'])->name('blog.articles.index');

    Route::get('/categories', [CategoriesController::class, 'index'])->name('blog.categories.index');
    Route::get('/categories/{category}', [CategoriesController::class, 'show'])->name('blog.categories.show');

    Route::get('auteurs', [UsersController::class, 'index'])->name('blog.users.index');
    Route::get('auteurs/{user}', [UsersController::class, 'show'])->name('blog.users.show');

    Route::get('crud/create', [ArticlesController::class, 'create'])->name('blog.crud.create');
    Route::post('crud/create', [ArticlesController::class, 'store'])->name('blog.crud.store');

    Route::get('crud/edit/{article}', [ArticlesController::class, 'edit'])->name('blog.crud.edit');
    Route::put('crud/edit/{article}', [ArticlesController::class, 'update'])->name('blog.crud.update');

    Route::delete('crud/delete/{article}', [ArticlesController::class, 'delete'])->name('blog.crud.destroy');

    Route::get('crud/categories/create', [CategoriesController::class, 'create'])->name('blog.crud.categories.create');
    Route::post('crud/categories/create', [CategoriesController::class, 'store'])->name('blog.crud.categories.store');

    Route::get('crud/categories/edit/{category}', [CategoriesController::class, 'edit'])->name('blog.crud.categories.edit');
    Route::put('crud/categories/edit/{category}', [CategoriesController::class, 'update'])->name('blog.crud.categories.update');

    Route::delete('crud/categories/delete/{category}', [CategoriesController::class, 'destroy'])->name('blog.crud.categories.destroy');

    Route::get('/{article}', [ArticlesController::class, 'show'])->name('blog.articles.show');
});

/**
 * Articles JSON
 */
Route::get('articles-json', [ArticlesJsonController::class, 'index'])->name('articles.json.index');
Route::get('articles-json/{iteration}', [ArticlesJsonController::class, 'show'])->whereNumber('iteration')->name('articles.json.show');
Route::get('authors-json/{name}', [ArticlesJsonController::class, 'author'])->name('articles.json.author');

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::withCount('articles')->orderBy('created_at', 'DESC')->get();
        return view('blog.users', compact('users'));
    }

    public function show(User $user)
    {
        $articles = Article::where('author_id', $user->id)->paginate(9);
        return view('blog.user', compact('user', 'articles'));
    }
}

resources/views/blog/article.blade.php
@extends('layouts.app')

@section('content')

    <div class="container py-5">
        <h1>{{ $article->title }}</h1>
        <img src="{{ $article->image_url }}" alt="{{ $article->title }}" class="w-100 img-fluid d-block">
        {!! $article->content !!}

        <div class="d-flex pt-4 justify-content-between align-items-center">
            @if( $article->author !== null )
                <div><a href="{{ route('blog.users.show', $article->author->id) }}">{{ $article->author->name }}</a></div>
            @endif
            <div>
                @foreach( $article->categories as $category )
                    <a href="{{ route('blog.categories.show', $category->id) }}">{{ $category->name }}</a>
                @endforeach
            </div>
        </div>
    </div>


@endsection

resources/views/blog/categories.blade.php
@extends('layouts.app')

@section('content')

    <div class="container py-5">
        <h1>Liste des catégories</h1>

        <a href="{{ route('blog.crud.categories.create') }}" class="btn btn-success btn-sm my-3">Créer une catégorie</a>

        <ul class="w-100">
            @foreach( $categories as $category )
                <li class="d-flex ">
                    <a href="{{ route('blog.categories.show', $category->id) }}">{{ $category->name }}</a> ({{ $category->articles_count }} articles)
                    <a class="btn btn-sm btn-primary ms-3" href="{{ route('blog.crud.categories.edit', [$category->id]) }}">Modifier</a></li>
                    <form method="POST" action="{{ route('blog.crud.categories.destroy', $category->id) }}">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-danger ms-3 btn-sm">Supprimer</button>
                    </form>
            @endforeach
        </ul>
    </div>

@endsection

resources/views/blog/category.blade.php
@extends('layouts.app')

@section('content')

    <div class="container py-5">
        <h1>Articles de la catégorie "{{ $category->name }}"</h1>

        @include('partials.articles', ['articles' => $articles])
    </div>

@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">
        <h1>Derniers articles publiés</h1>

        @include('partials.articles', ['articles' => $articles])
    </div>
@endsection

resources/views/blog/user.blade.php
@extends('layouts.app')

@section('content')

    <div class="container py-5">
        <h1>Articles de l'utilisateur "{{ $user->name }}"</h1>

        @include('partials.articles', ['articles' => $articles])
    </div>

@endsection

resources/views/blog/users.blade.php
@extends('layouts.app')

@section('content')

    <div class="container py-5">
        <h1>Liste des utilisateurs</h1>

        <ul>
            @foreach( $users as $user )
                <li><a href="{{ route('blog.users.show', $user->id) }}">{{ $user->name }}</a> ({{ $user->articles_count }} articles)</li>
            @endforeach
        </ul>
    </div>

@endsection